mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #刷新mapper 调试神器
    refresh: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker_str
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false