spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lims?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123456

